/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.ees.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/**
 * MyEclipse Struts Creation date: 04-08-2012
 * 
 * XDoclet definition:
 * 
 * @struts.form name="writeMailForm"
 */
public class WriteMailForm extends ActionForm {
	/*
	 * Generated fields
	 */

	private String sid;
	private String sname;
	/** details property */
	private String details;

	/** theme property */
	private String theme;

	/*
	 * Generated Methods
	 */

	/**
	 * Method validate
	 * 
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/**
	 * Method reset
	 * 
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/**
	 * Returns the details.
	 * 
	 * @return String
	 */

	public String getDetails() {
		return details;
	}

	public String getSid() {
		return sid;
	}

	public void setSid(String sid) {
		this.sid = sid;
	}

	public String getSname() {
		return sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	/**
	 * Set the details.
	 * 
	 * @param details
	 *            The details to set
	 */
	public void setDetails(String details) {
		this.details = details;
	}

	/**
	 * Returns the theme.
	 * 
	 * @return String
	 */
	public String getTheme() {
		return theme;
	}

	/**
	 * Set the theme.
	 * 
	 * @param theme
	 *            The theme to set
	 */
	public void setTheme(String theme) {
		this.theme = theme;
	}
}